name: Terraform Apply & Deploy
on:
  push:
    branches: [main]
    paths: ['infrastructure/**.tf', 'Dockerfile', 'index.html']
permissions:
  id-token: write
  contents: read
jobs:
  apply-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::463470960192:role/GitHubActionsRole
          aws-region: us-west-2
      - uses: hashicorp/setup-terraform@v3
      - name: Terraform Apply
        working-directory: infrastructure
        run: |
          terraform init -upgrade
          terraform apply -auto-approve
      - name: Login to ECR & Push & Deploy
        run: |
          # ここに前の手順で書いた Docker build & SSM デプロイのコマンドを記述
          echo "Build and Deploying..."